version: '3.8'

networks:
  mi_subnet:
    ipam:
      config:
        - subnet: 172.10.10.0/24

services:
  4ctf:
    container_name: ctf4
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
    networks:
      mi_subnet:
        ipv4_address: 172.10.10.6

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      mi_subnet:
        ipv4_address: 172.10.10.20
