FROM php:8.0-apache

# Instalar el paquete iputils-ping para habilitar el comando ping
RUN apt-get update && \
    apt-get install -y iputils-ping && \
    rm -rf /var/lib/apt/lists/*

COPY ./src/ /var/www/html

RUN echo 'fernandito:x:1000:1000::/home/fernandito:/bin/bash' >> /etc/passwd \
    && echo 'fernandito:Barman' | chpasswd

RUN groupadd fernandito && \
    chown fernandito:fernandito flag.txt && \
    chmod 600 flag.txt
