FROM dperson/samba:latest

# Copiar el archivo de configuración smb.conf en el directorio temporal del contenedor
COPY smb.conf /etc/samba/smb.conf

# Copiar el archivo de correo con la clave, texto cifrado y pista en el directorio compartido de Samba
COPY key.txt /var/lib/samba/public/key.txt
COPY readme.txt /var/lib/samba/public/readme.txt
COPY ciphertext.txt /var/lib/samba/public/ciphertext.txt

# Establecer los permisos para el archivo de correo
RUN chmod 644 /var/lib/samba/public/key.txt
RUN chmod 644 /var/lib/samba/public/readme.txt
RUN chmod 644 /var/lib/samba/public/ciphertext.txt