FROM ubuntu:19.10
RUN apt-get update

RUN useradd -d /home/ctf/ -m -p ctf -s /bin/bash ctf
RUN apt-get update && apt-get install -y openssh-server
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN echo "ctf:ctf" | chpasswd

WORKDIR /home/ctf

COPY flag.txt .

RUN chown -R root:root /home/ctf

USER ctf
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]