version: '3.8'

networks:
  mi_subnet:
    ipam:
      config:
        - subnet: 172.10.10.0/24

services:
  1ctf:
    build:
      context: ./CTF1
      dockerfile: dockerfile
    container_name: ctf1
    networks:
      mi_subnet:
        ipv4_address: 172.10.10.2

  2ctf:
    build:
      context: ./CTF2
      dockerfile: dockerfile
    container_name: ctf2
    networks:
      mi_subnet:
        ipv4_address: 172.10.10.3

  3ctf:
    build:
      context: ./CTF3
      dockerfile: dockerfile
    container_name: ctf3
    networks:
      mi_subnet:
        ipv4_address: 172.10.10.4

  4ctf:
    container_name: ctf4
    build:
      context: ./CTF4/
      dockerfile: dockerfile
    depends_on:
      - db
    networks:
      mi_subnet:
        ipv4_address: 172.10.10.6

  db:
    container_name: ctf4_db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
      - ./CTF4/sql/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      mi_subnet:
        ipv4_address: 172.10.10.20

  5ctf:
    container_name: ctf5
    build:
      context: ./CTF5/
      dockerfile: dockerfile
    networks:
      mi_subnet:
        ipv4_address: 172.10.10.7
  
  6ctf:
    container_name: ctf6
    build:
      context: ./CTF6/
      dockerfile: dockerfile
    networks:
      mi_subnet:
        ipv4_address: 172.10.10.8

  7ctf:
    container_name: ctf7
    build:
      context: ./CTF7/
      dockerfile: dockerfile
    networks:
      mi_subnet:
        ipv4_address: 172.10.10.9

  8ctf:
    container_name: ctf8
    build:
      context: ./CTF8/
      dockerfile: dockerfile
    networks:
      mi_subnet:
        ipv4_address: 172.10.10.10
  
  9ctf:
    container_name: ctf9
    build:
      context: ./CTF9/
      dockerfile: dockerfile
    networks:
      mi_subnet:
        ipv4_address: 172.10.10.11

  10ctf:
    container_name: ctf10
    build:
      context: ./CTF10/
      dockerfile: dockerfile
    networks:
      mi_subnet:
        ipv4_address: 172.10.10.11

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../portainer-data:/data
    ports:
      - 9000:9000