FROM ubuntu:20.04

# Instalación de actualizaciones y OpenSSH server
RUN apt-get update \
    && apt-get update && apt-get install -y sudo nano openssh-server

# Agregar usuario "fernandito" al archivo /etc/passwd con contraseña "strawberri"
RUN echo 'fernandito:x:1000:1000::/home/fernandito:/bin/bash' >> /etc/passwd \
    && echo 'fernandito:baseball' | chpasswd

# Permitir autenticación con contraseña y cambiar contraseña de fernandito
RUN mkdir /var/run/sshd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' \
    /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional \
    pam_loginuid.so@g' -i /etc/pam.d/sshd
RUN sed -i 's/#PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN sed -i 's/#MaxAuthTries 6/MaxAuthTries 100000000/' /etc/ssh/sshd_config

# Permitir a specialuser ejecutar nano como superusuario utilizando sudo
RUN echo "fernandito ALL=(ALL) NOPASSWD: /bin/nano" >> /etc/sudoers

# Establecer directorio de trabajo
WORKDIR /home/fernandito

# Copiar el archivo flag.txt en el contenedor
COPY flag.txt /root/
RUN chmod 700 /root/flag.txt
COPY readme.txt .

# Exponer el puerto 22
EXPOSE 22

# Ejecutar el servidor SSH
CMD ["/usr/sbin/sshd", "-D"]
