# Usa una imagen base de Apache
FROM httpd:2.4

# Copia los archivos de configuración personalizados a la imagen
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf

# Copia tu contenido web al directorio predeterminado de Apache
COPY ./index.html /usr/local/apache2/htdocs/