FROM php:8.0-apache

# Instalar el paquete iputils-ping y whois
RUN apt-get update && \
    apt-get install -y iputils-ping nmap && \
    rm -rf /var/lib/apt/lists/*

COPY ./src/ /var/www/html

RUN mkdir /mensajes
RUN mv /var/www/html/flag.txt /mensajes/

RUN chmod 755 /mensajes/flag.txt
