FROM ubuntu:20.04

# Instalación de actualizaciones y Instala OpenSSH server
RUN apt-get update \
    && apt-get update && apt-get install -y openssh-server

#Permite autenticación con contraseña y cambio de contraseá a root
RUN mkdir /var/run/sshd
RUN echo "root:strawberry" | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' \
    /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional \
    pam_loginuid.so@g' -i /etc/pam.d/sshd
RUN sed -i 's/#PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN sed -i 's/#MaxAuthTries 6/MaxAuthTries 100000000/' /etc/ssh/sshd_config
RUN service ssh restart
# Establece el directorio de trabajo
WORKDIR /root

# Copia el archivo flag.txt en el contenedor
COPY flag.txt .

# Establece el usuario a ctf y expone el puerto 22
EXPOSE 22

# Ejecuta el servidor SSH
CMD ["/usr/sbin/sshd", "-D"]