version: '3.8'

networks:
  mi_subnet:
    ipam:
      config:
        - subnet: 172.15.10.0/24

services:
  1ctf:
    build:
      context: ./CTF1
      dockerfile: dockerfile
    container_name: ctf1
    networks:
      mi_subnet:
        ipv4_address: 172.15.10.2

  2ctf:
    build:
      context: ./CTF2
      dockerfile: dockerfile
    container_name: ctf2
    networks:
      mi_subnet:
        ipv4_address: 172.15.10.3

  3ctf:
    build:
      context: ./CTF3
      dockerfile: dockerfile
    container_name: ctf3
    networks:
      mi_subnet:
        ipv4_address: 172.15.10.4