version: '3.8'

networks:
  mi_subnet:
    ipam:
      config:
        - subnet: 172.10.11.0/24

services:
  1ctf:
    container_name: ftp
    build:
      context: .
      dockerfile: dockerfile
    networks:
      mi_subnet:
        ipv4_address: 172.10.11.6
